site_name: Packet & Pen Docs
theme:
  name: material
  custom_dir: overrides
  features:
    - content.code.copy
    - content.code.annotate
extra_css:
  - css/terminal.css

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.highlight
  - codehilite:
      -linenums: true

plugins:
  - search


nav:
  - Home: index.md
  - Identity & Access Control:
    - Radius Server w/ GUI: identity-access-control/index.md
  - Network Automation:
    - In the Works: network-automation/index.md
  - Performance Testing:
    - In the Works: performance-testing/index.md
  - Infrastructure & DevOps:
    - In the Works: infrastructure-devops/index.md
  - Blog:
    - Check Back For Updates: blog/case-studies.md


