site_name: Packet & Pen Docs
theme:
  name: material
  features:
    - content.code.copy
    - content.code.annotate
extra_css:
  - css/terminal.css

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.highlight
  - codehilite:
      -linenums: true
nav:
  - Home: index.md
  - Identity & Access Control:
    - Radius Server w/ GUI: identity-access-control/index.md
  - Network Automation:
    - Overview: network-automation/index.md
  - Performance Testing:
    - Overview: performance-testing/index.md
  - Infrastructure & DevOps:
    - Overview: infrastructure-devops/index.md
  - Blog:
    - Case Studies: blog/case-studies.md

