# Deploy MKDocs site to GitHub Pages using official GitHub Pages actions

name: Deploy MKDocs to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write    # Required to push to the Pages branch
  pages: write       # Required for GitHub Pages deployment
  id-token: write    # Needed for OIDC token-based authentication

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Check out repository
        uses: actions/checkout@v4

      # Step 2: Set up Python so we can install MkDocs
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Step 3: Install MkDocs and the Material theme
      - name: Install dependencies
        run: |
          pip install mkdocs mkdocs-material jinja2-time

      # Step 4: Build the MkDocs site; this creates the "site" folder
      - name: Build site with MkDocs
        run: mkdocs build

      # Step 5: Upload the built site as an artifact for deployment
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site

      # Step 6: Deploy to GitHub Pages using the official deploy-pages action
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
